# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Interaktiv GmbH

stages:
  - test
  - docker

test:
  stage: test
  image: oven/bun:1
  before_script:
    - bun --version
  script:
    - bun install --frozen-lockfile
    - bun run typecheck
    - bun run lint
    - bun run format:check
    # Note: No unit tests yet, only integration tests via test-all.sh
    # - bun test
  only:
    - master

docker_prompt_tool:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "" # Required to disable TLS for DinD
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - export BRANCH_TAG=$(echo "$CI_COMMIT_REF_NAME" | tr '/' '-')
  script:
    - docker build -f Dockerfile -t "$CI_REGISTRY_IMAGE:$BRANCH_TAG" .
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        VERSION="${CI_COMMIT_TAG#v}"
        MAJOR=$(echo "$VERSION" | cut -d. -f1)
        MINOR=$(echo "$VERSION" | cut -d. -f2)

        if [ -z "$MAJOR" ] || [ -z "$MINOR" ]; then
          echo "Invalid semantic version tag: $CI_COMMIT_TAG"
          exit 1
        fi

        docker tag "$CI_REGISTRY_IMAGE:$BRANCH_TAG" "$CI_REGISTRY_IMAGE:$VERSION"
        docker tag "$CI_REGISTRY_IMAGE:$BRANCH_TAG" "$CI_REGISTRY_IMAGE:$MAJOR.$MINOR"
        docker tag "$CI_REGISTRY_IMAGE:$BRANCH_TAG" "$CI_REGISTRY_IMAGE:$MAJOR"
        docker tag "$CI_REGISTRY_IMAGE:$BRANCH_TAG" "$CI_REGISTRY_IMAGE:latest"

        docker push "$CI_REGISTRY_IMAGE:$BRANCH_TAG"
        docker push "$CI_REGISTRY_IMAGE:$VERSION"
        docker push "$CI_REGISTRY_IMAGE:$MAJOR.$MINOR"
        docker push "$CI_REGISTRY_IMAGE:$MAJOR"
        docker push "$CI_REGISTRY_IMAGE:latest"
      else
        docker push "$CI_REGISTRY_IMAGE:$BRANCH_TAG"
      fi
  only:
    - master
    - tags
